-- Your SQL goes here
CREATE TABLE movement (
  id INTEGER PRIMARY KEY NOT NULL,
  person_id INTEGER REFERENCES person(id) NOT NULL,
  value FLOAT NOT NULL,
  actor VARCHAR NOT NULL,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);